### ISSUE TITLE
marquee fixes needed 

### ISSUE THREAD

**Issue by Nowheres2go** [Nowheres2go/erinoisidori.online-redux#2]
- translate tickertape1 down in a similar vein of how tickertape2 runs along the top and bottom of its borders
- make marquee animation smoother
- fix bgcolor style in html files
- fix or add marquee text contents (maybe figure out infinite scroll or a better way that most of the text is new and fresh)
- tickertape3 needs scalex as opposed to scaley (also in a similar vein of how tickertape2 runs along the top and bottom of its borders)
- fix tickertape3 overflow over its top and bottom borders. (i.e. text short start AFTER the border at the top and end BEFORE the border on the bottom)

**Comment by webcrawls** [comment]
working TODO:
[ ] add top-to-bottom direction text for left side tickertape
[ ] switch from `<marquee>` to CSS animations
[ ] fix z-index/overflow (so text appears "above" the marquee's border)
