### ISSUE TITLE
post pages fixes needed

### ISSUE THREAD

**Issue by Nowheres2go** [Nowheres2go/erinoisidori.online-redux#4]
- scale images in accordance to their respective heights and widths but relative to the screen sized being used (dwh or something along those lines i can't think atm. artworks or blog images should have the full image including its margins without having to scroll to see the full thing. scrolling to find text is fine)
- maintain the margin around them when screen is changed 
- add forward and back arrows to pages themselves that take you respectively to the post before it or after it. there should be positioned almost like space between with the posts title in the middle and both arrows near the edge of the left and right sides (chronologically) (text arrows are in Buffalotub html file in artworks) 
- add css background animation (currently commented out in stylesheet)

-ADD BACK BUTTON TO POST

erino update:

- add new art add nomore duolgy
- add to new year new me and clothing design blog post
- add trying to write blog post
- maybe figure out a way to make posts feel a little more alive or animated in a minimal way

**Comment by webcrawls** [comment]
Closing this, we should re-evaluate and split this up into separate issues 🤙
